apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.23.4
      ports:
        - containerPort: 80
    - name: nginx-exporter
      image: 'nginx/nginx-prometheus-exporter:0.11'
      args:
        - '-nginx.scrape-uri=http://localhost/nginx_status'
      ports:
        - containerPort: 9113

