apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: nginx/
    repoURL: https://github.com/ikanago/k3s_suburi
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

